# Generated by Django 4.2.1 on 2023-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
            options={
                'ordering': ('name', 'quantity', 'distance'),
            },
        ),
    ]
